Require explicitly ActiveSupport Hash::Keys
Why:
Fixes error when running specs `bundle exec (/home/m/.rbenv/versions/3.1.0/bin/rspec)
bundle exec rspec spec/dsl_spec.rb`
```
NoMethodError:
undefined method `stringify_keys for {:name=>"Friday Order"}:Hash
...
dsl/endpoint.rb:171:in `block in extra_params
```